### PR TITLE
Interactive tutorial

### PR DESCRIPTION
**Pull request by blakerosenthal**
Adapted from Ben's verification script against TM1. This Jupyter notebook visualizes the `final_*.csv` outputs from a given ActivitySim run.

### CODE REVIEW

**Comment by bstabler** [comment]
This is coming along nicely.  Here are a few comments:
  - make the auto ownership maps full page width, change the breaks so there is more variance between the zones (i.e. not all the zones are basically purple), and create another map zoomed in on the urban areas (SF, Oakland, south bay, etc) so we can see all the small zone values as well
  - tour duration plots should be line graphs like https://github.com/ActivitySim/activitysim/wiki/verification/mtdd.xlsx since the dot plots can be difficult to interpret
  - tour mode choice needs a separate bar plot for each tour type like https://github.com/ActivitySim/activitysim/wiki/verification/tour_mode.xlsx
  - the last plot is mislabeled and should be trip mode and should also have separate bar plots for each type

**Comment by bstabler** [comment]
Let's add the shapefile to the folder as well

**Comment by blakerosenthal** [comment]
Great, thanks Ben. On it!

**Comment by bstabler** [comment]
For the map, use a single hue color palette since the map is showing intensity of one value.  See http://colorbrewer2.org/#type=sequential&scheme=Blues&n=3 for example.

**Comment by bstabler** [comment]
- Maps looks better
  - For Individual mandatory tour duration, split work and school into separate charts
  - For free parking, use the same color palette as CDAP so the colors used throughout the notebook are consistent

Thanks

**Comment by bstabler** [comment]
Looks good, thanks

**Comment by bstabler** [comment]
When I view the notebook on GitHub, https://github.com/RSGInc/activitysim/blob/fee05e6f93d7b6d99d72bd0f6d3b05469657a00a/scripts/verify_results.ipynb, it doesn't show the maps?

**Pull request merged**
